import { Product } from '../classes/products';
 
export const PRODUCTS: Product[] = [
        {id:"123",img:"assets/images/aprons.jpg",name:"Apron",mfg:"Manufacturar Name",price:1231,minOrder:100,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"124",img:"assets/images/Doctor Aprons.jpg",name:"Doctor Aprons",mfg:"Manufacturar Name",price:2231,minOrder:10,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"125",img:"assets/images/aprons1.jpg",name:"White Apron",mfg:"Manufacturar Name",price:3231,minOrder:110,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"126",img:"assets/images/Complete Bedset Strips.jpg",name:"Bed Sheet Strips",mfg:"Manufacturar Name",price:5231,minOrder:50,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureC"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"127",img:"assets/images/Colour Option.jpg",name:"Bed Sheet Strips",mfg:"Manufacturar Name",price:1231,minOrder:100,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"128",img:"assets/images/Colour Option 2.jpg",name:"Bed Sheet Strips",mfg:"Manufacturar Name",price:2231,minOrder:10,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"129",img:"assets/images/Colour Option 3.jpg",name:"Bed Sheet Strips",mfg:"Manufacturar Name",price:3231,minOrder:110,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"130",img:"assets/images/Bedsheet/Bedset - Hostel.jpg",name:"Bedset-Hostel",mfg:"Manufacturar Name",price:5231,minOrder:50,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureC"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"131",img:"assets/images/Bedsheet/Bedset Colour Option 1.jpg",name:"Bedset",mfg:"Manufacturar Name",price:1231,minOrder:100,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"132",img:"assets/images/Bedsheet/Bedset Colour Option 2.jpg",name:"Bedset",mfg:"Manufacturar Name",price:2231,minOrder:10,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"133",img:"assets/images/Bedsheet/Bedset Colour Option 3.jpg",name:"Bedset",mfg:"Manufacturar Name",price:3231,minOrder:110,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"134",img:"assets/images/Bedsheet/Bedset Colour Option.jpg",name:"Bedset",mfg:"Manufacturar Name",price:5231,minOrder:50,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureC"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"135",img:"assets/images/Bedsheet/Bedsteet + Pillow Cover.jpg",name:"Bedsteet + Pillow Cover",mfg:"Manufacturar Name",price:121,minOrder:70,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureC","FeatureB"],supplierRegion:["FeatureA","FeatureB"],description:""},
        {id:"136",img:"assets/images/Bedsheet/White Plain Bedsheet.jpg",name:"White Plain Bedsheet",mfg:"Manufacturar Name",price:7231,minOrder:150,location:"Banglore",feature:["FeatureA","FeatureB"],material:["FeatureA","FeatureB"],supplyType:["FeatureA","FeatureC"],supplierRegion:["FeatureA","FeatureB"],description:""}
];